import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="https://azwetbmrstagloadingdata.blob.core.windows.net/azwetbmrstagloadingdata/Slider/9/03b292f2-3f79-4379-b28f-8789ea79266b.jpg" alt="Vercel Logo" width={1200} height={75} />
          </span>
        </a>
      </footer>
    </div>
  )
}
